#version: '3.8'

services:
  goapp:
    container_name: apibl
    image: apibl:1.0.0
    build:
      context: .
      dockerfile: go.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - psqlbl

  psqlbl:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: