#version: '3.8'

services:
  goapp:
    container_name: api
    image: api:1.0.0
    build:
      context: .
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://${DB_DATABASE}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable'  
    ports:
      - '${PORT}:8000'
    depends_on:
      - psql

  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: